"""init pages and blocks

Revision ID: 6b5ea307d9b0
Revises: 
Create Date: 2026-05-07 11:49:02.764254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b5ea307d9b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('parent_page_id', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_parent_page_id'), 'pages', ['parent_page_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('page_id', sa.String(length=12), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parent_block_id', sa.String(length=12), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_page_id'), 'blocks', ['page_id'], unique=False)
    op.create_index(op.f('ix_blocks_parent_block_id'), 'blocks', ['parent_block_id'], unique=False)
    op.create_index(op.f('ix_blocks_position'), 'blocks', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blocks_position'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_parent_block_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_page_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_pages_parent_page_id'), table_name='pages')
    op.drop_table('pages')
    # ### end Alembic commands ###
